package Principal;
import Clases.Funcionario;
import Clases.MasterClass;
import javax.swing.JOptionPane;
public class FormFuncionario extends javax.swing.JFrame {
    MasterClass datos = new MasterClass();
    public void limpiar(){
        txt_CnombreFuncionario.setText("");
        txt_CapellidoFuncionario.setText("");
        txt_CemailFuncionario.setText("");
        txt_CtelefonoFuncionario.setText("");
        txt_CsedeFuncionario.setText("");
        txt_CnumeroFuncionario.setText("");
        txt_CpuestoFuncionario.setText("");
        txt_CdepartamentoFuncionario.setText("");

        txt_InombreFuncionario.setText("");
        txt_IapellidoFuncionario.setText("");
        txt_IemailFuncionario.setText("");
        txt_ItelefonoFuncionario.setText("");
        txt_IsedeFuncionario.setText("");
        txt_InumeroFuncionario.setText("");
        txt_IpuestoFuncionario.setText("");
        txt_IdepartamentoFuncionario.setText("");
    }
    public void imprimir(Funcionario arg){
        txt_CnombreFuncionario.setText(arg.getNombre());
        txt_CapellidoFuncionario.setText(arg.getApellido());
        txt_CemailFuncionario.setText(arg.getDireccionCorreo());
        txt_CtelefonoFuncionario.setText(arg.getTelefono());
        txt_CsedeFuncionario.setText(arg.getSede());
        txt_CnumeroFuncionario.setText(arg.getNumeroEmpleado());
        txt_CpuestoFuncionario.setText(arg.getPuesto());
        txt_CdepartamentoFuncionario.setText(arg.getDepartamento());
    }
    /**
     * Creates new form Funcionario
     */
    public FormFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txt_CnombreFuncionario = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_CapellidoFuncionario = new javax.swing.JTextField();
        txt_CemailFuncionario = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_CtelefonoFuncionario = new javax.swing.JTextField();
        txt_CsedeFuncionario = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_CnumeroFuncionario = new javax.swing.JTextField();
        txt_CpuestoFuncionario = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_CdepartamentoFuncionario = new javax.swing.JTextField();
        btn_buscarFuncionario = new javax.swing.JButton();
        btn_editarFuncionario = new javax.swing.JButton();
        btn_elimiarFuncionario = new javax.swing.JButton();
        btn_volver3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_CLibosAsignados = new javax.swing.JTextField();
        btn_primero = new javax.swing.JButton();
        btn_anterior = new javax.swing.JButton();
        btn_siguiente = new javax.swing.JButton();
        btn_ultimo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        txt_InombreFuncionario = new javax.swing.JTextField();
        txt_IapellidoFuncionario = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_IemailFuncionario = new javax.swing.JTextField();
        txt_ItelefonoFuncionario = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txt_IsedeFuncionario = new javax.swing.JTextField();
        txt_InumeroFuncionario = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txt_IpuestoFuncionario = new javax.swing.JTextField();
        txt_IdepartamentoFuncionario = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        bntGuardarFuncionario = new javax.swing.JButton();
        btn_volver4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(600, 300));

        jLabel16.setText("Nombre:");

        jLabel17.setText("Apellido:");

        jLabel18.setText("Direccion  de Correo:");

        jLabel19.setText("Telefono: ");

        jLabel20.setText("Sede:");

        jLabel21.setText("Numero de Empleado:");

        jLabel22.setText("Puesto a Desempanar");

        jLabel23.setText("Departamento");

        btn_buscarFuncionario.setText("Buscar");
        btn_buscarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarFuncionarioActionPerformed(evt);
            }
        });

        btn_editarFuncionario.setText("Editar");
        btn_editarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarFuncionarioActionPerformed(evt);
            }
        });

        btn_elimiarFuncionario.setText("Eliminar");
        btn_elimiarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_elimiarFuncionarioActionPerformed(evt);
            }
        });

        btn_volver3.setText("volver");
        btn_volver3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volver3ActionPerformed(evt);
            }
        });

        jLabel9.setText("Libros Asignados");

        btn_primero.setText("|<");
        btn_primero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_primeroActionPerformed(evt);
            }
        });

        btn_anterior.setText("<");
        btn_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anteriorActionPerformed(evt);
            }
        });

        btn_siguiente.setText(">");
        btn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteActionPerformed(evt);
            }
        });

        btn_ultimo.setText(">|");
        btn_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ultimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel17))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_CnombreFuncionario)
                            .addComponent(txt_CapellidoFuncionario)
                            .addComponent(txt_CemailFuncionario)
                            .addComponent(txt_CtelefonoFuncionario)
                            .addComponent(txt_CsedeFuncionario)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_primero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_anterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_siguiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ultimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_elimiarFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_volver3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel21)
                            .addComponent(jLabel9))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_CLibosAsignados, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(btn_buscarFuncionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_editarFuncionario))
                            .addComponent(txt_CnumeroFuncionario)
                            .addComponent(txt_CpuestoFuncionario)
                            .addComponent(txt_CdepartamentoFuncionario))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_CnombreFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_CapellidoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_CemailFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_CtelefonoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_CsedeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_CnumeroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_CpuestoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_CdepartamentoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_CLibosAsignados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_editarFuncionario)
                            .addComponent(btn_buscarFuncionario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_primero)
                        .addComponent(btn_siguiente)
                        .addComponent(btn_anterior)
                        .addComponent(btn_ultimo))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_elimiarFuncionario)
                        .addComponent(btn_volver3)))
                .addContainerGap())
        );

        jTabbedPane4.addTab("Consultar Funcionario", jPanel1);

        jLabel24.setText("Nombre:");

        jLabel25.setText("Apellido:");

        jLabel26.setText("Direccion  de Correo:");

        jLabel27.setText("Telefono: ");

        jLabel28.setText("Sede:");

        jLabel29.setText("Numero de Empleado:");

        jLabel30.setText("Puesto a Desempanar");

        jLabel31.setText("Departamento");

        bntGuardarFuncionario.setText("Guardar");
        bntGuardarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGuardarFuncionarioActionPerformed(evt);
            }
        });

        btn_volver4.setText("volver");
        btn_volver4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volver4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bntGuardarFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addComponent(btn_volver4)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel24)
                                .addComponent(jLabel26)
                                .addComponent(jLabel27)
                                .addComponent(jLabel28)
                                .addComponent(jLabel25))
                            .addGap(46, 46, 46)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_InombreFuncionario)
                                .addComponent(txt_IapellidoFuncionario)
                                .addComponent(txt_IemailFuncionario)
                                .addComponent(txt_ItelefonoFuncionario)
                                .addComponent(txt_IsedeFuncionario)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel30)
                                .addComponent(jLabel31)
                                .addComponent(jLabel29))
                            .addGap(44, 44, 44)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_InumeroFuncionario)
                                .addComponent(txt_IpuestoFuncionario)
                                .addComponent(txt_IdepartamentoFuncionario))))
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(262, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntGuardarFuncionario)
                    .addComponent(btn_volver4))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(txt_InombreFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_IapellidoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_IemailFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_ItelefonoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_IsedeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_InumeroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel29))
                    .addGap(6, 6, 6)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_IpuestoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_IdepartamentoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel31))
                    .addContainerGap(76, Short.MAX_VALUE)))
        );

        jTabbedPane4.addTab("Ingresar Funcionario", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_volver3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volver3ActionPerformed
        FormPrincipal selcam = new FormPrincipal();
        selcam.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_volver3ActionPerformed

    private void btn_volver4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volver4ActionPerformed
        FormPrincipal selcam = new FormPrincipal();
        selcam.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_volver4ActionPerformed

    private void btn_primeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_primeroActionPerformed
        if(datos.primeroF()==null){
            JOptionPane.showMessageDialog(rootPane, "No hay datos a Mostrar");
        }else{
            imprimir(datos.primeroF());
        }
    }//GEN-LAST:event_btn_primeroActionPerformed

    private void btn_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anteriorActionPerformed
        if(datos.primeroF()==null){
            JOptionPane.showMessageDialog(rootPane, "No hay datos a Mostrar");
        }else{
            imprimir(datos.anteriorF());
        }
    }//GEN-LAST:event_btn_anteriorActionPerformed

    private void btn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteActionPerformed
        if(datos.primeroF()==null){
            JOptionPane.showMessageDialog(rootPane, "No hay datos a Mostrar");
        }else{
            imprimir(datos.siguenteF());
        }
    }//GEN-LAST:event_btn_siguienteActionPerformed

    private void btn_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ultimoActionPerformed
        if(datos.primeroF()==null){
            JOptionPane.showMessageDialog(rootPane, "No hay datos a Mostrar");
        }else{
            imprimir(datos.ultimoF());
        }
    }//GEN-LAST:event_btn_ultimoActionPerformed

    private void btn_buscarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarFuncionarioActionPerformed
        if(datos.primeroF()==null){
            JOptionPane.showMessageDialog(rootPane, "No hay datos a Mostrar");
        }else{
            imprimir(datos.buscarF(txt_CnombreFuncionario.getText()));
        }
    }//GEN-LAST:event_btn_buscarFuncionarioActionPerformed

    private void btn_elimiarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_elimiarFuncionarioActionPerformed
        if(datos.primeroF()==null){
            JOptionPane.showMessageDialog(rootPane, "No hay datos a Mostrar");
        }else{
            datos.eliminarF(txt_CnombreFuncionario.getText());
        }
        limpiar();
    }//GEN-LAST:event_btn_elimiarFuncionarioActionPerformed

    private void btn_editarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarFuncionarioActionPerformed
        if(datos.primeroF()==null){
            JOptionPane.showMessageDialog(rootPane, "No hay datos a Mostrar");
        }else{
            datos.modificarF(txt_CnombreFuncionario.getText(),txt_CapellidoFuncionario.getText(),
                    txt_CemailFuncionario.getText(),txt_CtelefonoFuncionario.getText(),txt_CsedeFuncionario.getText(), 
                    txt_CnumeroFuncionario.getText(),txt_CpuestoFuncionario.getText(), 
                    txt_CdepartamentoFuncionario.getText());
        }
        limpiar();
    }//GEN-LAST:event_btn_editarFuncionarioActionPerformed

    private void bntGuardarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGuardarFuncionarioActionPerformed
        if(txt_InombreFuncionario.getText().isEmpty() || txt_IapellidoFuncionario.getText().isEmpty()
                || txt_IemailFuncionario.getText().isEmpty() || txt_ItelefonoFuncionario.getText().isEmpty()
                || txt_IsedeFuncionario.getText().isEmpty() || txt_InumeroFuncionario.getText().isEmpty()
                || txt_IpuestoFuncionario.getText().isEmpty()|| txt_IdepartamentoFuncionario.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Debe llenar todos los campos");
        }else{
            datos.guardarF(txt_InombreFuncionario.getText(), txt_IapellidoFuncionario.getText(), 
                    txt_IemailFuncionario.getText(), txt_ItelefonoFuncionario.getText(),
                    txt_IsedeFuncionario.getText(), txt_InumeroFuncionario.getText(),
                    txt_IpuestoFuncionario.getText(), txt_IdepartamentoFuncionario.getText());
        }
        limpiar();
    }//GEN-LAST:event_bntGuardarFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntGuardarFuncionario;
    private javax.swing.JButton btn_anterior;
    private javax.swing.JButton btn_buscarFuncionario;
    private javax.swing.JButton btn_editarFuncionario;
    private javax.swing.JButton btn_elimiarFuncionario;
    private javax.swing.JButton btn_primero;
    private javax.swing.JButton btn_siguiente;
    private javax.swing.JButton btn_ultimo;
    private javax.swing.JButton btn_volver3;
    private javax.swing.JButton btn_volver4;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextField txt_CLibosAsignados;
    private javax.swing.JTextField txt_CapellidoFuncionario;
    private javax.swing.JTextField txt_CdepartamentoFuncionario;
    private javax.swing.JTextField txt_CemailFuncionario;
    private javax.swing.JTextField txt_CnombreFuncionario;
    private javax.swing.JTextField txt_CnumeroFuncionario;
    private javax.swing.JTextField txt_CpuestoFuncionario;
    private javax.swing.JTextField txt_CsedeFuncionario;
    private javax.swing.JTextField txt_CtelefonoFuncionario;
    private javax.swing.JTextField txt_IapellidoFuncionario;
    private javax.swing.JTextField txt_IdepartamentoFuncionario;
    private javax.swing.JTextField txt_IemailFuncionario;
    private javax.swing.JTextField txt_InombreFuncionario;
    private javax.swing.JTextField txt_InumeroFuncionario;
    private javax.swing.JTextField txt_IpuestoFuncionario;
    private javax.swing.JTextField txt_IsedeFuncionario;
    private javax.swing.JTextField txt_ItelefonoFuncionario;
    // End of variables declaration//GEN-END:variables
}
