/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;
import Clases.DataSolicitudes;
import Clases.Estudiante;
import Clases.Funcionario;
import Clases.Libro;
import Clases.MasterArchivos;
import Clases.MasterClass;
import Clases.Profesor;
import Clases.Solicitudes;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class FormSolictarLibro extends javax.swing.JFrame {
    MasterClass datos = new MasterClass();
    DataSolicitudes data = new DataSolicitudes();
    
    public void imprimir(Estudiante arg){
        txt_Apellido.setText(arg.getApellido());
        txt_Email.setText(arg.getDireccionCorreo());
        txt_Telefono.setText(arg.getTelefono());
        txt_Cede.setText(arg.getSede());
    }
    public void imprimir(Funcionario arg){
        txt_Apellido.setText(arg.getApellido());
        txt_Email.setText(arg.getDireccionCorreo());
        txt_Telefono.setText(arg.getTelefono());
        txt_Cede.setText(arg.getSede());
    }
    public void imprimir(Profesor arg){
        txt_Apellido.setText(arg.getApellido());
        txt_Email.setText(arg.getDireccionCorreo());
        txt_Telefono.setText(arg.getTelefono());
        txt_Cede.setText(arg.getSede());
    }
    public void imprimir(Libro arg){
        txt_TituloLibro.setText(arg.getNombreLibro());
        txt_libroResumen.setText(arg.getNombreLibro());
        txt_librosAlmacenados.setText(arg.getCantidadLibrosDisponibles());
    }
     public void imprimir(Solicitudes arg){
       txt_librosAsignadosP.setText(arg.getLibAsignados());
       txt_TituloLibro.setText(arg.getNombLibro());
    }
    
    /**
     * Creates new form SolictarLibro
     */
    public FormSolictarLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_atras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_Apellido = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Telefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_Cede = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_TituloLibro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_Accion = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btn_enviarSolicitud = new javax.swing.JButton();
        txt_TipoPersona = new javax.swing.JComboBox<>();
        btn_buscarSolicitarLibro = new javax.swing.JButton();
        btn_CargarDatos = new javax.swing.JButton();
        txt_CantidadLibros = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txt_librosAlmacenados = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_librosDisponibles = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txt_libroResumen = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        BuscarTitulo = new javax.swing.JButton();
        txt_librosAsignadosP = new javax.swing.JTextField();
        btn_botonBuscarlibroSiguiente = new javax.swing.JButton();
        btn_botonBuscarlibroAnterior = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btn_verificarPersona = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));

        btn_atras.setText("Atras");
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre: ");

        jLabel2.setText("Email:");

        jLabel3.setText("Apellido:");

        txt_Apellido.setEditable(false);

        txt_Email.setEditable(false);

        jLabel4.setText("Telefono:");

        txt_Telefono.setEditable(false);

        jLabel5.setText("Cede:");

        txt_Cede.setEditable(false);

        jLabel6.setText("Tipo Persona:");

        jLabel7.setText("Titulo del Libro:");

        jLabel8.setText("Cantidad Libros: ");

        txt_Accion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entregar Libro", "Solicitar Libro" }));

        jLabel9.setText("Accion:");

        btn_enviarSolicitud.setText("Enviar Solicitud");
        btn_enviarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarSolicitudActionPerformed(evt);
            }
        });

        txt_TipoPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Funcionario", "Estudiante", "Profesor" }));

        btn_buscarSolicitarLibro.setText("Buscar Persona");
        btn_buscarSolicitarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarSolicitarLibroActionPerformed(evt);
            }
        });

        btn_CargarDatos.setText("Cargar Data");
        btn_CargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CargarDatosActionPerformed(evt);
            }
        });

        jLabel10.setText("Libros de Biblioteca:");

        txt_librosAlmacenados.setEditable(false);

        jLabel11.setText("Libros Disponibles:");

        txt_librosDisponibles.setEditable(false);

        jLabel12.setText("Solicitud Resumen:");

        txt_libroResumen.setEditable(false);
        txt_libroResumen.setEnabled(false);

        BuscarTitulo.setText("Buscar Titulo");
        BuscarTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarTituloActionPerformed(evt);
            }
        });

        txt_librosAsignadosP.setEditable(false);

        btn_botonBuscarlibroSiguiente.setText(">");
        btn_botonBuscarlibroSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_botonBuscarlibroSiguienteActionPerformed(evt);
            }
        });

        btn_botonBuscarlibroAnterior.setText("<");
        btn_botonBuscarlibroAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_botonBuscarlibroAnteriorActionPerformed(evt);
            }
        });

        jLabel13.setText("Asignados a persona:");

        btn_verificarPersona.setText("Verificar Persona");
        btn_verificarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verificarPersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(8, 8, 8)
                                        .addComponent(txt_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btn_buscarSolicitarLibro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Cede, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_TipoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_CargarDatos)))
                .addGap(0, 27, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txt_TituloLibro))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_librosAlmacenados)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_librosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_librosAsignadosP, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BuscarTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_botonBuscarlibroAnterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_botonBuscarlibroSiguiente)))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_libroResumen)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_CantidadLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txt_Accion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_enviarSolicitud)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_atras)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_verificarPersona)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel12)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_TipoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_CargarDatos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_Cede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarSolicitarLibro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_TituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_librosAlmacenados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txt_librosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_botonBuscarlibroSiguiente)
                    .addComponent(btn_botonBuscarlibroAnterior)
                    .addComponent(txt_librosAsignadosP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_verificarPersona)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(txt_libroResumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_CantidadLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(txt_Accion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_enviarSolicitud)
                    .addComponent(btn_atras))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
        FormPrincipal selcam = new FormPrincipal();
        selcam.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_atrasActionPerformed

    private void btn_buscarSolicitarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarSolicitarLibroActionPerformed
        String TipoPersona = txt_TipoPersona.getSelectedItem().toString();
        if(TipoPersona.equalsIgnoreCase("Funcionario")){
            imprimir(datos.buscarF(txt_Nombre.getText()));
        }else if(TipoPersona.equalsIgnoreCase("Estudiante")){
            imprimir(datos.buscarE(txt_Nombre.getText()));  
        }else if(TipoPersona.equalsIgnoreCase("Profesor")){
            imprimir(datos.buscarP(txt_Nombre.getText()));
        }
    }//GEN-LAST:event_btn_buscarSolicitarLibroActionPerformed

    private void btn_CargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CargarDatosActionPerformed
        String TipoPersona = txt_TipoPersona.getSelectedItem().toString();
        
        if(TipoPersona.equalsIgnoreCase("Funcionario")){
            Funcionario funcionario = new Funcionario();
            String linea;FileReader f = null;
            try {
                f = new FileReader("Funcionarios.txt");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MasterClass.class.getName()).log(Level.SEVERE, null, ex);
            }
            try (BufferedReader b = new BufferedReader(f)) {
                while ((linea = b.readLine()) != null) {
                    String orden[] = linea.split(",");
                    funcionario.setNombre(orden[0]);
                    funcionario.setApellido(orden[1]);
                    funcionario.setDireccionCorreo(orden[2]);
                    funcionario.setTelefono(orden[3]);
                    funcionario.setSede(orden[4]);
                    funcionario.setNumeroEmpleado(orden[5]);
                    funcionario.setPuesto(orden[6]);
                    funcionario.setDepartamento(orden[7]);
                    datos.guardarF(funcionario.getNombre(), funcionario.getApellido(), 
                        funcionario.getDireccionCorreo(), funcionario.getTelefono(),
                        funcionario.getSede(), funcionario.getNumeroEmpleado(),
                        funcionario.getPuesto(), funcionario.getDepartamento());
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }else if(TipoPersona.equalsIgnoreCase("Estudiante")){
            Estudiante estudiante = new Estudiante();
            String linea;FileReader f = null;
            try {
                f = new FileReader("Estudiantes.txt");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MasterClass.class.getName()).log(Level.SEVERE, null, ex);
            }
            try (BufferedReader b = new BufferedReader(f)) {
                while ((linea = b.readLine()) != null) {
                    String orden[] = linea.split(",");
                    estudiante.setNombre(orden[0]);
                    estudiante.setApellido(orden[1]);
                    estudiante.setDireccionCorreo(orden[2]);
                    estudiante.setTelefono(orden[3]);
                    estudiante.setSede(orden[4]);
                    estudiante.setNumeroCarnet(orden[5]);
                    estudiante.setCarreraCursando(orden[6]);
                    estudiante.setEstatus(orden[7]);

                    datos.guardarE(estudiante.getNombre(), estudiante.getApellido(), 
                        estudiante.getDireccionCorreo(), estudiante.getTelefono(),
                        estudiante.getSede(), estudiante.getNumeroCarnet(),
                        estudiante.getCarreraCursando(), estudiante.getEstatus());
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }else if(TipoPersona.equalsIgnoreCase("Profesor")){
            Profesor profesor = new Profesor();
            String linea;FileReader f = null;
            try {
                f = new FileReader("profesores.txt");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MasterClass.class.getName()).log(Level.SEVERE, null, ex);
            }
            try (BufferedReader b = new BufferedReader(f)) {
                while ((linea = b.readLine()) != null) {
                    String orden[] = linea.split(",");
                    profesor.setNombre(orden[0]);
                    profesor.setApellido(orden[1]);
                    profesor.setDireccionCorreo(orden[2]);
                    profesor.setTelefono(orden[3]);
                    profesor.setSede(orden[4]);
                    profesor.setCodigoMarca(orden[5]);
                    profesor.setCantidadCursosqueImparte(orden[6]);
                    datos.guardarP(profesor.getNombre(), profesor.getApellido(), 
                        profesor.getDireccionCorreo(), profesor.getTelefono(),
                        profesor.getSede(), profesor.getCodigoMarca(),
                        profesor.getCantidadCursosqueImparte());
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }  
        //############Cargar datos de Libro##########################
        Libro libro = new Libro();
        String linea;FileReader f = null;
        try {
            f = new FileReader("Libros.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MasterClass.class.getName()).log(Level.SEVERE, null, ex);
        }
        try (BufferedReader b = new BufferedReader(f)) {
            while ((linea = b.readLine()) != null) {
                String orden[] = linea.split(",");
                libro.setNombreLibro(orden[0]);
                libro.setAutor(orden[1]);
                libro.setFechaPublicacion(orden[2]);
                libro.setEditorial(orden[3]);
                libro.setCantidadLibrosDisponibles(orden[4]);
                datos.guardarL(libro.getNombreLibro(), libro.getAutor(), 
                    libro.getFechaPublicacion(), libro.getEditorial(),
                    libro.getCantidadLibrosDisponibles());
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        //############Cargar datos de Solicitudes##########################
        Solicitudes solicitud = new Solicitudes();
        String lineas;FileReader file = null;
        try {
            file = new FileReader("Reservaciones.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DataSolicitudes.class.getName()).log(Level.SEVERE, null, ex);
        }
        try (BufferedReader b = new BufferedReader(file)) {
            while ((lineas = b.readLine()) != null) {
                String orden[] = lineas.split(",");
                solicitud.setNombSolicitante(orden[0]);
                solicitud.setNombLibro(orden[1]);
                solicitud.setLibAsignados(orden[2]);

                data.guardar(solicitud.getNombSolicitante(), solicitud.getNombLibro(), 
                        solicitud.getLibAsignados());
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_CargarDatosActionPerformed

    private void btn_enviarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarSolicitudActionPerformed
        /*boolean encontrado=false;  
        Libro libro = new Libro();
        String linea;FileReader f = null;
        try {
            f = new FileReader("Libros.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MasterClass.class.getName()).log(Level.SEVERE, null, ex);
        }
        try (BufferedReader b = new BufferedReader(f)) {
            while ((linea = b.readLine()) != null) {
                String orden[] = linea.split(",");
                libro.setNombreLibro(orden[0]);
                libro.setAutor(orden[1]);
                libro.setFechaPublicacion(orden[2]);
                libro.setEditorial(orden[3]);
                libro.setCantidadLibrosDisponibles(orden[4]);
               
                if(libro.getNombreLibro().equalsIgnoreCase(txt_TituloLibro.getText())){
                    encontrado=true;
                }                
            }  
            
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        if(encontrado){
            String TipoPersona = txt_TipoPersona.getSelectedItem().toString();
                    
            String valor = txt_CantidadLibros.getValue().toString();
            int cantidad = Integer.parseInt(valor);  

            if(TipoPersona.equalsIgnoreCase("Funcionario")){
                Funcionario obF = new Funcionario();
                obF.cantidadLibrosPrestados(cantidad, TipoPersona);
            }else if(TipoPersona.equalsIgnoreCase("Estudiante")){
                Estudiante obE = new Estudiante();
                System.out.print(obE.cantidadLibrosPrestados(cantidad, TipoPersona));
                JOptionPane.showMessageDialog(null, "Solicitud enviada");
                
            }else if(TipoPersona.equalsIgnoreCase("Profesor")){
                imprimir(datos.buscarP(txt_Nombre.getText()));
            }
        }else{
           JOptionPane.showMessageDialog(null, "Libro no encontrado"); 
        }*/
        MasterArchivos reserva = new MasterArchivos();
        if(txt_Accion.getSelectedItem().toString().equalsIgnoreCase("Solicitar Libro")){
            //Libro li = new Libro();
            int c1 = Integer.parseInt(txt_librosAlmacenados.getText());
            int c2 = Integer.parseInt(txt_CantidadLibros.getValue().toString());
            
            String resto = Integer.toString(c1-c2);
            
            reserva.GuardarArchivo(txt_Nombre.getText(),txt_libroResumen.getText(),txt_CantidadLibros.getValue().toString());
                   
            reserva.GuardarArchivolibro(txt_libroResumen.getText(), resto);
            JOptionPane.showMessageDialog(null, "Solicitud Recibida");
            
        }else if(txt_Accion.getSelectedItem().toString().equalsIgnoreCase("Entregar Libro")){
            int c3 = Integer.parseInt(txt_librosDisponibles.getText());
            int c4 = Integer.parseInt(txt_CantidadLibros.getValue().toString());
            String operacion2 = Integer.toString(c3+c4);
            try{
                BufferedReader files = new BufferedReader(new FileReader("Reservaciones2.txt"));
                String lines;String input = "";
                while((lines = files.readLine()) != null){
                    /* Podemos verificar si es Usuario_1 y \r\n es para hacer el 
                      Salto de Línea y tener el formato original */
                    if(lines.contains(txt_libroResumen.getText())){
                        input += lines.replaceAll(txt_librosDisponibles.getText(),operacion2)+"\r\n";
                        //input += "\n";
                    }else{
                        input += lines+"\r\n";
                    }
                        
                }
                FileOutputStream fileOut = new FileOutputStream("Reservaciones2.txt");
                fileOut.write(input.getBytes());
                fileOut.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "Dato no modificado");
            }

            int c1 = Integer.parseInt(txt_librosAsignadosP.getText());
            int c2 = Integer.parseInt(txt_CantidadLibros.getValue().toString());
            
            //int operacion = c1-c2;
            String operacion = Integer.toString(c1-c2);
            
            try{
                BufferedReader file = new BufferedReader(new FileReader("Reservaciones.txt"));
                String line;String input = "";
                while((line = file.readLine()) != null){
                    /* Podemos verificar si es Usuario_1 y \r\n es para hacer el 
                      Salto de Línea y tener el formato original */
                    if(line.contains(txt_Nombre.getText())){
                        input += line.replaceAll(txt_librosAsignadosP.getText(),operacion)+"\r\n";
                        //input += "\n";
                    }else{
                        input += line+"\r\n";
                    }
                        
                }
                FileOutputStream fileOut = new FileOutputStream("Reservaciones.txt");
                fileOut.write(input.getBytes());
                fileOut.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "Dato no modificado");
            }
 
        }
        //limpiarL();
        FormPrincipal selcam = new FormPrincipal();
        selcam.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btn_enviarSolicitudActionPerformed

    private void BuscarTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarTituloActionPerformed
        
        
        imprimir(datos.buscarL(txt_TituloLibro.getText()));
        //imprimir(data.buscar(txt_Nombre.getText()));
        
        //String linea;FileReader f = null;
        //String libros ="", resto ="";
        /*try {
            f = new FileReader("Reservaciones.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MasterClass.class.getName()).log(Level.SEVERE, null, ex);
        }
        try (BufferedReader b = new BufferedReader(f)) {
            while ((linea = b.readLine()) != null) {
                String orden[] = linea.split(",");
                libros=orden[2];
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e);
        }*/
        
        /*try {
            f = new FileReader("Reservaciones2.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MasterClass.class.getName()).log(Level.SEVERE, null, ex);
        }
        try (BufferedReader b = new BufferedReader(f)) {
            while ((linea = b.readLine()) != null) {
                String orden[] = linea.split(",");
                resto=orden[1];
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e);
        }*/
        
        
        /*imprimir(datos.buscarL(txt_TituloLibro.getText()));
        txt_librosAsignadosP.setText(libros);
        txt_librosDisponibles.setText(resto);*/
    }//GEN-LAST:event_BuscarTituloActionPerformed

    private void btn_botonBuscarlibroAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_botonBuscarlibroAnteriorActionPerformed
        imprimir(datos.anteriorL());
        //imprimir(data.anterior());
    }//GEN-LAST:event_btn_botonBuscarlibroAnteriorActionPerformed

    private void btn_botonBuscarlibroSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_botonBuscarlibroSiguienteActionPerformed
        imprimir(datos.siguenteL());
        //imprimir(data.siguente());
    }//GEN-LAST:event_btn_botonBuscarlibroSiguienteActionPerformed

    private void btn_verificarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verificarPersonaActionPerformed
        String linea;FileReader f = null;
        String  resto ="";
        Solicitudes solicitud = new Solicitudes();
               
        try {
            f = new FileReader("Reservaciones.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MasterClass.class.getName()).log(Level.SEVERE, null, ex);
        }
        try (BufferedReader b = new BufferedReader(f)) {
            while ((linea = b.readLine()) != null) {
                String orden[] = linea.split(",");
                //libros=orden[2];
                solicitud.setNombSolicitante(orden[0]);
                solicitud.setNombLibro(orden[1]);
                solicitud.setLibAsignados(orden[2]);
            }
            data.guardar(solicitud.getNombSolicitante(), solicitud.getNombLibro(), solicitud.getLibAsignados());
            
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
                
        try {
            f = new FileReader("Reservaciones2.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MasterClass.class.getName()).log(Level.SEVERE, null, ex);
        }
        try (BufferedReader b = new BufferedReader(f)) {
            while ((linea = b.readLine()) != null) {
                String orden[] = linea.split(",");
                resto=orden[1];
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        if(txt_Nombre.getText().equalsIgnoreCase(solicitud.getNombSolicitante())){
            
            imprimir(data.buscar(txt_Nombre.getText()));
            txt_librosDisponibles.setText(resto);
            imprimir(datos.buscarL(txt_TituloLibro.getText()));
        }
        
        
    }//GEN-LAST:event_btn_verificarPersonaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSolictarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSolictarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSolictarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSolictarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSolictarLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarTitulo;
    private javax.swing.JButton btn_CargarDatos;
    private javax.swing.JButton btn_atras;
    private javax.swing.JButton btn_botonBuscarlibroAnterior;
    private javax.swing.JButton btn_botonBuscarlibroSiguiente;
    private javax.swing.JButton btn_buscarSolicitarLibro;
    private javax.swing.JButton btn_enviarSolicitud;
    private javax.swing.JButton btn_verificarPersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<String> txt_Accion;
    private javax.swing.JTextField txt_Apellido;
    private javax.swing.JSpinner txt_CantidadLibros;
    private javax.swing.JTextField txt_Cede;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_Telefono;
    private javax.swing.JComboBox<String> txt_TipoPersona;
    private javax.swing.JTextField txt_TituloLibro;
    private javax.swing.JTextField txt_libroResumen;
    private javax.swing.JTextField txt_librosAlmacenados;
    private javax.swing.JTextField txt_librosAsignadosP;
    private javax.swing.JTextField txt_librosDisponibles;
    // End of variables declaration//GEN-END:variables
}
